/**
 * Passaporte Clio
 * API REST que conecta pessoas a museus.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CriaPresencaMuseuDto } from './criaPresencaMuseuDto';
import { CriaPresencaUserDto } from './criaPresencaUserDto';
import { Link } from './link';

export interface CriaPresencaDto { 
    id?: number;
    museu: CriaPresencaMuseuDto;
    data?: Date;
    autor?: CriaPresencaUserDto;
    links?: Array<Link>;
}