/**
 * Passaporte Clio
 * API REST que conecta pessoas a museus.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EnderecoDto } from './enderecoDto';
import { Link } from './link';

export class MuseusDto { 
    id?: number;
    nome: string = '';
    descricaoMuseu: string= '';
    funcionamentoMuseu: string= '';
    urlFoto: string = '';
    urlSite: string = '';
    urlInstagram: string = '';
    endereco: EnderecoDto = new EnderecoDto ;
   
}