/**
 * Passaporte Clio
 * API REST que conecta pessoas a museus.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CriaPresencaUserDto } from './criaPresencaUserDto';
import { Link } from './link';
import { MuseusDto } from './museusDto';

export interface PresencaDto { 
    id?: number;
    museu: MuseusDto;
    data: string;
    autor?: CriaPresencaUserDto;
    links?: Array<Link>;
}